title: Pharmalium privacy and policy
description: all pharmalium privacy and policy details

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
 
theme: jekyll-theme-minimal
include:
  - PRIVACYPOLICY.md
markdown: kramdown
